// listings.js
export const listingsData = [
    {
      id: 1,
      title: "House in Khayaban-e-Amin",
      price: 12000000,
      locationDetails: "Phase 1, Block L",
      bedrooms: 3,
      bathrooms: 3,
      propertyType: "House",
      image: "/images/house3.jpg",
      squareFootage: "5 Marlas",
      parking: "2 car parking",
      listingAdded: "Added 1 hour ago",
      highlight: "Near Main Road",
      age: "Built in 2020",
      status: "For Sale",
      description: "Welcome to this charming residence in the heart of Khayaban-e-Amin. This isn't just a house - it's a thoughtfully designed living space that combines modern comfort with practical elegance. Nestled in a peaceful neighborhood yet minutes away from essential amenities, this home offers the perfect balance of convenience and tranquility. The property features bright, airy rooms with large windows that welcome natural light, creating an inviting atmosphere throughout. The modern kitchen is equipped with quality fixtures, perfect for both daily cooking and entertaining. With its strategic location near main roads and local amenities, this home provides both accessibility and a serene living environment. The property also includes beautifully landscaped outdoor spaces, offering a perfect setting for morning coffee or evening tea."
    },
    {
        id: 2,
        title: "Duplex, Johar Town, Block-A",
        price: 25000000,
        locationDetails: "123 Main St, Johar Town",
        bedrooms: 4,
        bathrooms: 3,
        propertyType: "House",
        image: "/images/house1.jpg",
        squareFootage: "10 Marlas",
        parking: "3 car parking",
        listingAdded: "Added 1 hour ago",
        highlight: "Prime Location",
        age: "Built in 2019",
        status: "For Sale",
        description: "Discover luxury living in this prestigious Johar Town duplex. This residence redefines modern family living with its thoughtful design and premium finishes. Located in the highly sought-after Block-A, this home seamlessly blends contemporary architecture with practical living spaces. The ground floor features an open-concept living area that flows into a modern kitchen, perfect for family gatherings. Upstairs, you'll find generously sized bedrooms, each designed to maximize comfort and privacy. The master suite includes a walk-in closet and an ensuite bathroom with premium fixtures. The property's location offers easy access to educational institutions, shopping centers, and healthcare facilities. With its spacious layout and prime location, this duplex isn't just a home - it's a lifestyle upgrade."
      },
      {
        id: 3,
        title: "House in DHA Phase 6", 
        price: 35000000,
        locationDetails: "Plot 55, Sector J",
        bedrooms: 2,
        bathrooms: 2,
        propertyType: "Plot",
        image: "/images/house4.jpg",
        squareFootage: "1 Kanal",
        parking: "4 car parking",
        listingAdded: "Added 1 hour ago",
        highlight: "Corner Plot",
        age: "Built in 2022",
        status: "For Sale",
        description: "Experience elevated living in this prestigious DHA Phase 6 corner property. This architectural masterpiece stands as a testament to modern design and luxury living. The corner location provides enhanced privacy and abundant natural light from multiple directions. The home features an intelligent layout that maximizes space utilization while maintaining an elegant flow between areas. High ceilings and large windows create an atmosphere of openness and grandeur. The property includes a state-of-the-art kitchen, formal and informal living areas, and a private garden perfect for outdoor entertaining. Its location in DHA Phase 6 offers proximity to premium schools, restaurants, and shopping centers, making it an ideal choice for families seeking a sophisticated lifestyle."
      },
      {
        id: 4,
        title: "Apartment in Gulberg",
        price: 18000000,
        locationDetails: "4th Floor, Liberty Heights",
        bedrooms: 3,
        bathrooms: 2,
        propertyType: "Apartment",
        image: "/images/house2.jpeg",
        squareFootage: "2 Kanals",
        parking: "2 car parking",
        listingAdded: "Added 1 hour ago",
        highlight: "City View",
        age: "Built in 2021",
        status: "For Sale",
        description: "Welcome to this stunning apartment in the prestigious Liberty Heights, where urban sophistication meets comfortable living. This isn't just an apartment - it's a viewpoint over the vibrant heart of Gulberg. From its elevated position on the 4th floor, enjoy breathtaking city views through floor-to-ceiling windows that flood the space with natural light. The open-concept living area creates a perfect entertainment space, while the modern kitchen features premium appliances and elegant finishes. Each bedroom serves as a private retreat, with the master suite offering spectacular city views. The building's amenities include 24/7 security, dedicated parking, and a rooftop garden. Located in the heart of Gulberg, you're steps away from high-end shopping, dining, and entertainment venues."
      },
    // more listings...
  ];